### ISSUE TITLE
Overwrites existing pianobar config

### ISSUE THREAD

**Issue by pixelherodev** [MycroftAI/pianobar-skill#27]
I already use pianobar, but I feed it my password via my password manager. I was able to modify this for my personal use to not mess with my config and not require my password in plaintext, but I feel like there should really be a fix for this here (which is a separate issue I'm going to report shortly).

When a pianobar config already exists, it shouldn't be overwritten. Appending the event handler, sure, but that can be done without overwriting other custom settings.

**Comment by krisgesling** [comment]
Hey, this should be slightly improved with mycroft-core v20.8.1 and PR #42
 
Further improvements to local Skill settings handling are on their way.
