### ISSUE TITLE
missing license - breaking copyright

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/pianobar-skill#41]
this skill does not provide a license, you need to contact ethanaward from which this skill was forked and clarify this situation

`When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 
`

https://choosealicense.com/no-permission/

I am surprised an official skill does not have a license, especially because as highlighted above you are essentially modifying and distributing copyrighted code!

this also impacts end users, since we might not be permitted to use the skill at all

`If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
`

**Comment by krisgesling** [comment]
Sorry I missed this over the holidays, but thanks for flagging it.

There are license details in the python files but to make it clear that it covers everything in the repo Ethan's added a license file to his upstream project and we've pulled that in to this fork.

It's MIT licensed.
